In [2]:
import utils.image_analysis_utils as iau

In [5]:
NPZ = "exports/outputs/sonar_cones_run.npz"

df = iau.analyze_run_largest_blob(
    NPZ,
    blur_ksize=70, blur_sigma=10.0,          # stronger blur if your data is speckly
    thr_percentile=80, min_area_px=80,   # tweak these two the most
    open_close=1,
    save_csv="exports/outputs/largest_blob.csv",
    save_mp4="exports/outputs/largest_blob.mp4",
    fps=15, progress=True
)

df.head()

[largest_blob] t=0/699  area=19430
[largest_blob] t=100/699  area=23951
[largest_blob] t=200/699  area=13454
[largest_blob] t=300/699  area=16632
[largest_blob] t=400/699  area=17707
[largest_blob] t=500/699  area=16880
[largest_blob] t=600/699  area=20954
[largest_blob] wrote video → exports/outputs/largest_blob.mp4
[largest_blob] wrote csv → exports/outputs/largest_blob.csv

,t_idx,ts,cx_px,cy_px,x_m,y_m,x0,y0,x1,y1,area_px,method
0,0,2024-08-20 11:40:23.268609+00:00,449.714462,297.736541,0.004132,4.259464,286,238,622,358,19430,classical_largest_blob
1,1,2024-08-20 11:40:23.268609+00:00,440.333389,295.631057,-0.176608,4.229343,260,238,595,350,18057,classical_largest_blob
2,2,2024-08-20 11:40:23.268609+00:00,436.714359,295.416092,-0.246333,4.226267,243,239,604,355,19563,classical_largest_blob
3,3,2024-08-20 11:40:23.268609+00:00,437.869342,294.020357,-0.224081,4.206300,231,238,597,349,20435,classical_largest_blob
4,4,2024-08-20 11:40:23.268609+00:00,423.451200,292.018595,-0.501867,4.177662,216,204,595,360,20758,classical_largest_blob